esheldon/fitsio

fitsio/__init__.py, fitsio/fitslib.py, fitsio/test.py
avoid interfering with stdout in a non-controlable way.
=> convert print to warnings.

fitsio/fitslib.py, fitsio/test.py
astype does the wrong thing. we want to view the same memory
chunk as an int.
Seriously, we need to develop reading numpy documentations
as a bed side hobby.
This PR fixes  #39
=> fix all False boolean for some versions of numpy.

setup.py
=> removed -iarch in setup.py

setup.py
Refile issue #63 for further development.
=> Use a subclass of build_ext to build cfitsio.

setup.py
=> WIP: Cfitsio build ext

.travis.yml, setup.py
I roughly followed the guide in  
https://github.com/scipy/scipy/pull/4890#issuecomment-153198355
to create this new PR. 
To resolve the conflicts, I used
git checkout -3 setup.py .travis.yml 
then manually patched #71 .
=> Cfitsio build ext2

fitsio/fitslib.py, fitsio/test.py
Added kwarg to allow ignoring call to _ensure_empty_image_ok() function.
=> Added ignore_empty option to allow the writing of empty (no data) HDUs 0

CHANGES.md, README.md, fitsio/__init__.py, fitsio/fitsio_pywrap.c, fitsio/fitslib.py, fitsio/test.py, setup.py
new features for resizing tables, as well as deleting sets and ranges of rows
=> Feature row modifications

fitsio/fitslib.py
this is a first shot at this. Mainly forcing str type and
converting known strings using a function rather than '%s',
which will put a b in front and not evaluate equal in many
situations
=> trying to santitize py3 string input

fitsio/fitslib.py, fitsio/test.py
These changes enable GZIP_2 compression which is now available on newer version of cfitsio.
=> Updates to enable GZIP_2 compression

README.md
This PR adds extra docs.
Closes #170
=> DOC add conda-forge instructions

setup.py
=> Remove ccache from compiler args if it is present

.travis.yml, fitsio/fitslib.py, fitsio/test.py
This PR has support for numpy 'U' dtypes in python 3.
Closes #179
=> ENH numpy 'U' dtype support for python 3

.gitignore, MANIFEST.in, setup.py
I think you need this to upload sdists to pypi. 
Before:
```bash
$ ls -1 fitsio-1.0.0rc1
LICENSE.txt
MANIFEST.in
PKG-INFO
README.md
fitsio
fitsio.egg-info
setup.cfg
setup.py
```
After:
```bash
$ ls -1 fitsio-1.0.0rc1
LICENSE.txt
MANIFEST.in
PKG-INFO
README.md
cfitsio3430patch
fitsio
fitsio.egg-info
setup.cfg
setup.py
```
I also updated the `setup.py` to tell pypi how to display the README correctly.
=> ENH package the C code too

setup.py
Something that annoyed me since a long time ;), Numpy should not be required to run the setup. Also it seems that the Numpy import was duplicated, and include_dirs was defined twice.
So instead this PR relies on setuptools to install Numpy eggs with setup_requires, and
uses a delayed import of Numpy to get the include_dirs.
=> Don't require numpy to run the setup

fitsio/__init__.py, fitsio/fitslib.py, setup.py
This PR has some minor changes to how we handle unicode. 
Closes #192
=> minor unicode changes

README.md, fitsio/fitslib.py, fitsio/test.py, setup.py
This PR fixes
- repatching is now tried and exceptions are caught
- shape testing for columns catches a corner case (closes #206)
- adds easier testing docs
=> fixes for reinstall, docs, error catching

CHANGES.md, README.md
=> update changelog and readme

fitsio/fitslib.py, fitsio/test.py
=> ensure comment is preserved when setting header value of existing entry

fitsio/fitslib.py, fitsio/test.py
=> raise ValueError if strings have size 0. Add test

fitsio/fitsio_pywrap.c
=> Use fits_write_key_longstr to write strings

fitsio/fitsio_pywrap.c
=> Write compression for values >= 0

fitsio/fitslib.py, fitsio/test.py
Also mention the behavior will change to align with numpy / h5py.
Fix #177
=> Add deprecation warning indexing by scalar.

CHANGES.md, README.md, fitsio/__init__.py, fitsio/fitslib.py, setup.py
Some preparations for reasing v1.0.1, mainly doc changes, version bump, etc.
=> v1.0.1prep

fitsio/__init__.py, fitsio/fitslib.py, fitsio/hdu/__init__.py, fitsio/hdu/base.py, fitsio/hdu/image.py, fitsio/hdu/table.py, fitsio/header.py, fitsio/test.py, fitsio/util.py, setup.py
This PR refactors the library into more files etc.
=> REF refactor into more files

fitsio/fitsio_pywrap.c, fitsio/hdu/table.py, fitsio/test.py
=> #240 deal with bitcols when inserting column

fitsio/fitslib.py
=> run expandvars on filename in read_header

fitsio/header.py, fitsio/test.py
closes #250 
this is used when the user adds cards directly
also added a test
=> put _convert_string back in for bools

fitsio/header.py
=> deal with None names in get()

fitsio/fitsio_pywrap.c
=> check LONGLONG first for int64 image dtype

fitsio/hdu/table.py, fitsio/test.py
Also see: https://github.com/bccp/nbodykit/issues/606
=> Fix error reading with an empty rows argument.

fitsio/fitsio_pywrap.c, fitsio/fitslib.py
=> Fpack in filename

CHANGES.md, fitsio/fitslib.py, fitsio/hdu/base.py, fitsio/hdu/image.py, fitsio/hdu/table.py, fitsio/header.py
I messed up. Now I am paying my penance.
Closes #279 
Closes #291
=> BUG fix deprecation warnings

fitsio/fitslib.py
When we created the file and haven't created anything, we will not
closes #290
=> BUG disallow getitem when file created but no data

CHANGES.md, README.md, fitsio/__init__.py, fitsio/fitsio_pywrap.c, fitsio/fitslib.py, fitsio/test.py
closes #304 
TODO:
Possible TODO
=> Quantization levels and dithering options

fitsio/header.py
=> don't remove BLANK cards in header clean

.github/workflows/tests.yml, .travis.yml, CHANGES.md, README.md
This PR adds GHA for linux and osx. It also moves travis to ppc64le tests only.
closes #314
=> ENH added GHA and do ppc64le on travis

CHANGES.md, fitsio/__init__.py, setup.py
=> bump version to 1.1.5 and update CHANGES.md

fitsio/header.py, fitsio/test.py
This PR fixes #337 and adds a new unit test.
Closes #337
=> BUG fix list assignment index out of range (#337)

CHANGES.md, fitsio/__init__.py, fitsio/header.py, setup.py
closes #343 
also removed old code to avoid an ancient gcc 4 bug
=> fix bugs in header repr

fitsio/fitsio_pywrap.c
=> ensure extname is ascii

CHANGES.md, fitsio/fitslib.py
closes #352 
An indentation error, the for loop should be outside the if
=> bug in repr only printing first time

.github/workflows/tests.yml, CHANGES.md, fitsio/test.py
=> ENH remove pkg_resources; update tests

.github/workflows/tests.yml, setup.py
=> BUG get external builds working again

.gitignore, CHANGES.md, setup.py
This may help with #369. Needs testing.
=> BUG ensure our headers come first

.gitignore, CHANGES.md, fitsio/fitsio_pywrap.c, setup.py
This PR tries to hide all of the cfitsio symbols from the python extension so that the linker does not get confused.
=> ENH hide all symbols

patches/fitsio2.h.patch
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.
Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html
=> Add support for LoongArch.

CHANGES.md, fitsio/fitslib.py, fitsio/tests/test_image_compression.py
closes #387 
Need to reopen the file for cfitsio to get the keywords right.  Not exactly sure where the bug is
=> work around cfitsio bug creating HDU for lossless gzip

CHANGES.md, fitsio/__init__.py, fitsio/hdu/image.py, fitsio/tests/test_empty_slice.py, setup.py
=> FIX empty slice case

CHANGES.md
=> prod: release 1.2.5

.github/workflows/tests.yml, CHANGES.md, fitsio/__init__.py, fitsio/hdu/table.py, fitsio/tests/test_table.py, setup.py
closes #426 
This version keeps old behavior
=> Make string vector length 1 work for numpy 2

.github/workflows/wheel.yml, pyproject.toml, setup.py
=> feat: move to pyproject.toml
