fitsio/test.py
I have to say the generation of the test data does look a bit messy.
this is an update to #39 . 
It really is a patch work hard coding those 'b1' and '?'. 
I do note that b1 and ? are treated the same way, possibly due to compatibility concerns. New code was supposed to used '?', I vaguely remember seeing it somewhere but I may have been wrong.
=> update the test as suggested by erin

setup.py
This is a reimplementation of my previous pull request esheldon/fitsio#27. It adds the ability to build fitsio against the system cfitsio install. I tested the changes on my mac with python 2.7.10 and it worked fine. This pull request conflicts with esheldon/fitsio#52 (moving `include_dirs` to the extenstion build). I have implemented this change too.
=> added option to setup.py to use system cfitsio

setup.py
Just remove the .so files to force a rebuild. We should probably
implement a new 'command' or target type for building cfitsio to
properly resolve this -- beyond my knowlege for now.
This fixes #65
=> Do not purge the full tree for a rebuild.

.travis.yml
This travis-ci only tests the build and install of the package.
Enable this by flipping the switch on esheldon/fitsio after logging in at travis-ci.org. 
https://api.travis-ci.org/esheldon/fistio.svg shall contain the build status badge.
Note that the test cases in test.py are not enabled in travis. 
As there are currently 1 failure with 2 errors.
=> Add travis-ci.

.travis.yml, setup.py
Note that the proper way of setting up these 'build_ext' options is via explicitly adding build_ext subcommand on the commandline, e.g.
```
python setup.py install build_ext --use-system-fitsio
``
=> customize includedir and libdir of system cfitsio.

.travis.yml
miniconda update has renamed the default installation path to miniconda2.
=> Travis-CI: set miniconda prefix.

fitsio/fitsio_pywrap.c
`tile_dims_fits` is on the cfitsio side, so its type should be `long`. This fixes #83.
=> Fix crash on 32-bit platforms

fitsio/fitsio_pywrap.c
On MIPS and PowerPC, `sizeof(long) == 4`, so that one cannot replace `npy_int64` with `long` there. On MIPS, this leads to a [Floating point exception](https://buildd.debian.org/status/fetch.php?pkg=python-fitsio&arch=mips&ver=0.9.8%2Bdfsg-2&stamp=1460908617)
in `testImageSlice` (division by 0, since the stepsize is then errornously set to zero).
On PowerPC, this is catched, but [leads to a failure `testImageSlice`](https://buildd.debian.org/status/fetch.php?pkg=python-fitsio&arch=powerpc&ver=0.9.8%2Bdfsg-2&stamp=1460846389). On both platforms, `testImageWriteReadFromDimsChunks` and `testImageWriteReadFromDims` fail as well.
This patch uses `npy_int64` on the places where these problems appear.
With this patch, [PowerPC](https://buildd.debian.org/status/fetch.php?pkg=python-fitsio&arch=pow …
=> Fix more 32-bit sizeof issues

fitsio/fitslib.py, fitsio/test.py
This pull request fixes partially #86, in the sense that one can now use tables that have a `dtype=numpy.dtype(..., align=True)` set. It also includes a fix for the ASCII table test to use aligned data. This is the only test that fails on the ARM platform (so, when applying this pull request, all tests for ARM [succeed](https://buildd.debian.org/status/fetch.php?pkg=python-fitsio&arch=armhf&ver=0.9.8%2Bdfsg-5&stamp=1461280405)); however for Sparc64 the other tests also result in a [segmentation fault] (https://buildd.debian.org/status/fetch.php?pkg=python-fitsio&arch=sparc64&ver=0.9.8%2Bdfsg-5&stamp=1461359715). I am not shure whether it is generally better to
- leave the decision to the user to use the `align` argument of `numpy.dtype` if he wants to use his software those platforms …
=> Allow aligned data

fitsio/fitsio_pywrap.c, fitsio/fitslib.py, fitsio/test.py
This PR closes #117 by treating `CONTINUE` cards like `COMMENT` cards. This is not a full implementation of the `CONTINUE` convention documented [here](https://fits.gsfc.nasa.gov/registry/continue_keyword.html), which is left to be addressed by #118.
=> Treat CONTINUE card like COMMENT

README.md, fitsio/__init__.py, fitsio/fitsio_pywrap.c, fitsio/fitslib.py, fitsio/test.py
It is occasionally useful to be able to use fitsio on files which you
have already read into memory through other means. The cfitsio library
supports this with fits_open_memfile/fits_create_memfile.
This feature was developed with the use case of a thumbnail server in
mind. In our implementation, FITS files are received over HTTPS from the
network, immediately converted into a JPEG, and then sent out over HTTPS
to the client. By keeping everything in memory, the requests are
processed a little bit faster, and we don't need to worry about filling
up our disks with temporary files over time.
To keep the code simple, we have exclusively implemented support for
read-only operation using fits_open_memfile. The existing implementation
can already create temporary FITS files in memory, and then …
=> Support read-only in memory files (using fits_open_memfile)

setup.py
Because fitsio uses it sinh, tanh, and similar functions.
=> Link against libm.

fitsio/fitslib.py, fitsio/test.py
I was running into some errors when reading DES Y3 fits files that had "CONTINUE=" lines (rather than CONTINUE with out the =).  I don't know if this is FITS-standard-conforming or not, but it seems like it is worth fitsio supporting this syntax.
=> Add test of real DES header with CONTINUE= and fix to work.

fitsio/fitsio_pywrap.c, fitsio/fitslib.py, fitsio/test.py
This addresses issue #173 
when writing, a None value for a header keyword will trigger writing a header key with undefined (blank) value.
when reading, these are converted to None values
=> Deal properly with undefined header keywords

fitsio/fitslib.py, fitsio/test.py
These were being converted to integers in py3: '1_000_000'
add tests for this and the binary operation '25-3' case
fix bug with binary op case setting wrong value
addressed #167
=> preserve strings with underscores as strings

fitsio/fitslib.py, fitsio/test.py
If the entry is a string, don't even try to convert it.
Also remove extra convert attempt; this is not needed because conversion happens in the FITSCard
=> #207 fix issues converting string header entries

fitsio/fitsio_pywrap.c, fitsio/fitslib.py, fitsio/test.py
long strings are read correctly (via CONTINUE)
now all keyword values are read into long strings and converted in the python code.
=> Fix long string reading in FITS headers

fitsio/fitslib.py
This PR fixes a bug in `fitsio.read_header()` where it was comparing a capitalized EXTNAME to a previously lower-cased extname, and thus not finding the HDU.  Attached is a gzip-ed file for testing if you want to try a different solution.
Current master:
```
$> python -c "import fitsio; fitsio.read_header('cmx-targets.fits', 'TARGETS')"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/sbailey/anaconda3/envs/fitsiotest/lib/python3.7/site-packages/fitsio-1.0.1-py3.7-macosx-10.7-x86_64.egg/fitsio/fitslib.py", line 188, in read_header
'hdu not found: %s (extver %s)' % (extname, extver))
OSError: hdu not found: TARGETS (extver None)
```
With this PR:
```
$> python -c "import fitsio; fitsio.read_header('cmx-targets.fits', 'TARGETS')"
[no error]
``` …
=> fix EXTNAME case comparison in read_header()

fitsio/fitsio_pywrap.c, fitsio/hdu/base.py, fitsio/header.py, fitsio/test.py
closes #249 
the current version writes them correctly when adding cards as a dict
todo
=> fixes for writing comments with blank keywords

fitsio/fitsio_pywrap.c, fitsio/test.py
Fixes #266 
This will check for a `HISTORY` keyword and treat it like a comment and call `add_string_to_dict` for the `comment` value.
A test has been added for it as well.
=> Fixes the HISTORY keyword having a None value when read in.

fitsio/hdu/image.py, fitsio/test.py
Fixes #264 
Specifying a step in an image slice should shrink the dimension of the output.
```python
import fitsio
import numpy
fits = fitsio.FITS('file.fits', 'rw')
data = numpy.arange(10000).reshape(100,100)
fits.write(data)
hdu = fits[-1]
cut = hdu[:,10:50:8]. # Starting at pixel 10, step every 8th pixel until the 50th one along the second axis.
cut.shape
```
Will output:
```python
(100, 5)
```
Rather than:
```python
(100, 40)
```
This is useful when slicing a large portion of a larger image but want to skip some pixels to save space.
=> Add fix to allow striding.

fitsio/fitsio_pywrap.c, fitsio/hdu/base.py, fitsio/hdu/image.py, fitsio/test.py
This is to add a feature to the `base.py` to use the `ignore_scaling` flag on an HDU before reading the data from it.  Default value is `False` to preserve existing functionality.
This is useful when the `BZERO` AND `BSCALE` values are set to scale the pixels, but the user/caller wants to cut from the original pixels.
The API ice used like this:
```python
import fitsio
fits = fitsio.FITS('file.fits', 'r'). # File with BZERO=23.5 and BSCALE=0.4 for example.
hdu_1 = fits[1]
cut_1 = hdu_1[20:100,:]. # Will return scaled slice (BZERO+DAT*BSCALE)
hdu_1.ignore_scaling = True
cut_2 = hdu_1[20:100,:]. # Will return unscaled slice (BZERO=0.0, BSCALE=1.0)
```
**Note**:
In order for tests to pass, this relies on the `test.py` fixes from PR #271.
=> Scaling ignore feature 262

CHANGES.md, README.md, fitsio/hdu/image.py, fitsio/test.py
Fixes #268 
This will likely conflict with PR #274 .
This feature enables a caller to slice along an axis in reverse.
```python
import fitsio
import numpy
fits = fitsio.FITS('outputfile.fits', 'rw', clobber=True)
dtype = numpy.int16
data = numpy.arange(100 * 200, dtype=dtype).reshape(100, 200)
fits.write_image(data)
hdu = fits[-1]
rdata = hdu[:,130:70]
rdata.shape # Will be (100, 60)
ndatacut = data[:,130:70:-1]. # Equivalent to numpy directly.
ndatacut.shape # Will be (100, 60)
```
=> Support flipping along the axis when slicing

fitsio/hdu/table.py, fitsio/test.py
I ran into this bug when adding a feature to TreeCorr that would read only every nth row in the input catalog.  It worked when start or stop were specified, but not when reading from the whole range.
=> Fix bug when reading slice with step, but no start/stop

fitsio/hdu/table.py
Fixes:
fitsio/hdu/table.py:234: SyntaxWarning: "is" with a literal. Did you mean "=="?
if data.shape is ():
fitsio/hdu/table.py:234: SyntaxWarning: "is" with a literal. Did you mean "=="?
if data.shape is ():
Error found in https://github.com/Homebrew/homebrew-core/pull/47326
=> Fix table.py for Python 3.8

CHANGES.md, README.md, fitsio/__init__.py, fitsio/fitsio_pywrap.c, setup.py
For non-keywords the non-ascii characters are replaced
with '?'
For keywords some attempt is made to produce a new keyword that would be
valid, although this is not checked.
closes #295
=> convert header garbage to ascii

fitsio/fitsio_pywrap.c, fitsio/header.py
closes #293 
Store `card_string` in the header entries read from disk.
These can contain incomplete data, so for repr we use a fake card that can be longer
=> Store card string

fitsio/fitsio_pywrap.c, fitsio/test.py
closes #277 
don't use reading by key name for comments and history
This fixes a bug where comments and history were returned in the wrong
order.  They share the same name, so reading by name is the wrong thing
in this case.
=> Fix comment order in returned header object

fitsio/hdu/table.py, fitsio/test.py
The `append()` method did not forward the `columns` and `names` arguments to `write()`.
=> append() not forwarding arguments

fitsio/test.py
Starting with version 4.1.0, CFITSIO removed the SUBTRACTIVE_DITHER_2
option has been removed when using the HCOMPRESS algorithm. Drop the
corresponding test on the fitsio side so that the testsuite still
passes.
=> testCompressPreserveZeros: do not test with the hcompress algorithm

CHANGES.md, README.md, fitsio/fitsio_pywrap.c, fitsio/hdu/table.py, fitsio/tests/test_table.py
closes #367 
If the users sends `rows = [3, 1]` the old code returned data for `[1, 3]`.  The data are now returned as requested.
Also previously duplicate rows were removed, no longer.
=> Return table data in order requested by user

CHANGES.md, fitsio/fitsio_pywrap.c, patches/fitsio.h.patch
This should help with #369. It adds the function declaration if we are bundling cfitsio and we have not included the right header. Note that this situation is very bad in general since the header API may not match, but cfitsio is stable enough that I suspect this is safe enough.
=> ENH add extra header guards

CHANGES.md, fitsio/__init__.py, fitsio/fitsio_pywrap.c, fitsio/tests/test_image_compression.py, setup.py
closes #385 
Even when set to 0 we need to write it.  This support lossless compression
Note however this has uncovered a second bug, where for the lossless gzip compression the data are not being flushed/finalized while the fits object is open
=> fix bug not writing qlevel

CHANGES.md, fitsio/__init__.py, fitsio/hdu/table.py, fitsio/tests/test_table.py, setup.py
closes #407 
Check for TBIT columns when slicing and rows read
=> check TBIT for slices/rows read

.github/workflows/tests.yml, CHANGES.md, fitsio/fitsio_pywrap.c, fitsio/fitslib.py, fitsio/tests/test_image_compression.py
closes #351
Add ability to seed the subtractive dither
=> Seed dithering

.github/dependabot.yml, .github/workflows/tests.yml, .github/workflows/wheel.yml
This PR adds wheel builds.
to do:
=> feat: build wheels

CHANGES.md, fitsio/fitsio_pywrap.c, fitsio/tests/test_header.py
This fixes https://github.com/esheldon/fitsio/issues/420
=> fix has_quote detection to handle free-form string values in header cards

fitsio/fitsio_pywrap.c, fitsio/tests/test_image_compression.py
In the `legacypipe` code, we use `mem://` files very extensively -- this allows us to do in-memory checksums before writing to disk.
We also use compression extensively, which we set at the file level via extended filename syntax - eg we create files like
```
fits = fitsio.FITS('mem://[compress R 100,100; qz -1e-4]', 'rw')
```
However, we find that when doing this, when you go to write an image HDU, the compression parameters don't get passed through because `compress=` is not set.
This patch fixes that.
Test case: these two files should get the same `ZDITHER0` set.
```
import numpy as np
import fitsio
A = ((1+np.arange(10000)) * 0.1).astype(np.float32)
fitsio.write('dither1.fits', A.copy(), dither_seed='checksum', compress='RICE', qlevel=1e-4,
tile_dims=100, clobber=True)
hdr = …
```
=> When using file-level compression, allow setting compression parameters
